{{- $applicationName := .Values.application.name -}}
{{- $deployment := .Values.deployment -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $deployment.name | default $applicationName }}-allow-ingress
  namespace: {{ $deployment.namespace | default $applicationName }}
spec:
  podSelector:
    matchLabels:
      app: {{ $applicationName }}
  policyTypes:
  - Ingress
  ingress:
    - from: []