{{- $applicationName := .Values.application.name -}}
{{- $service := .Values.service -}}
{{- $deployment := .Values.deployment -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $deployment.name | default $applicationName }}
  namespace: {{ $deployment.namespace | default $applicationName }}
spec:
  {{- if $service.ports }}
  ports:
    {{- range $port := $service.ports }}
    - port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      protocol: {{ $port.protocol | default "TCP" }}
    {{- end }}
  {{- end }}
  type: {{ $service.type }}
  selector:
    app: {{ $applicationName }}